export const class_data = [
  {
    id: "TURMA001",
    nome: "10A - Ciências",
    ano: "Primeiro Ano",
    turno: "Matutino",
    quantidadeAlunos: 30,
    status: "Ativa",
    professorResponsavel: "Ana Silva",
  },
  {
    id: "TURMA002",
    nome: "10B - Matemática",
    ano: "Primeiro Ano",
    turno: "Vespertino",
    quantidadeAlunos: 28,
    status: "Ativa",
    professorResponsavel: "Carlos Oliveira",
  },
  {
    id: "TURMA003",
    nome: "11A - História",
    ano: "Segundo Ano",
    turno: "Noturno",
    quantidadeAlunos: 25,
    status: "Ativa",
    professorResponsavel: "Maria Santos",
  },
  {
    id: "TURMA004",
    nome: "11B - Física",
    ano: "Segundo Ano",
    turno: "Matutino",
    quantidadeAlunos: 32,
    status: "Inativa",
    professorResponsavel: "Roberto Almeida",
  },
];
