export const subject_data = [
  {
    id: "DISC001",
    nome: "Matemática",
    codigo: "MAT101",
    cargaHoraria: "80h",
    professor: "Carlos Oliveira",
    turma: "10B",
  },
  {
    id: "DISC002",
    nome: "História",
    codigo: "HIS102",
    cargaHoraria: "60h",
    professor: "Maria Santos",
    turma: "11A",
  },
  {
    id: "DISC003",
    nome: "Física",
    codigo: "FIS103",
    cargaHoraria: "90h",
    professor: "Roberto Almeida",
    turma: "11B",
  },
  {
    id: "DISC004",
    nome: "Química",
    codigo: "QUI104",
    cargaHoraria: "70h",
    professor: "Ana Silva",
    turma: "10A",
  },
  {
    id: "DISC005",
    nome: "Inglês",
    codigo: "ING105",
    cargaHoraria: "50h",
    professor: "Mariana Costa",
    turma: "10B",
  },
];
